#!/usr/bin/env sh

set -ex

: "${SET_IPTABLES_DEV:=eth0}"
: "${SET_IPTABLES_PROXY_PORT:=3128}"

# Example ruleset for a transparent proxy
iptables -D PREROUTING -t nat -i "${SET_IPTABLES_DEV}" -p tcp --dport 80  -j REDIRECT --to-port "${SET_IPTABLES_PROXY_PORT}" || true
iptables -D PREROUTING -t nat -i "${SET_IPTABLES_DEV}" -p tcp --dport 443 -j REDIRECT --to-port "${SET_IPTABLES_PROXY_PORT}" || true
iptables -A PREROUTING -t nat -i "${SET_IPTABLES_DEV}" -p tcp --dport 80  -j REDIRECT --to-port "${SET_IPTABLES_PROXY_PORT}"
iptables -A PREROUTING -t nat -i "${SET_IPTABLES_DEV}" -p tcp --dport 443 -j REDIRECT --to-port "${SET_IPTABLES_PROXY_PORT}"
